-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_matmul_10ul_1ul_4ul_Pipeline_VITIS_LOOP_71_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    agg_result_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    agg_result_3_ce0 : OUT STD_LOGIC;
    agg_result_3_we0 : OUT STD_LOGIC;
    agg_result_3_d0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    agg_result_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    agg_result_2_ce0 : OUT STD_LOGIC;
    agg_result_2_we0 : OUT STD_LOGIC;
    agg_result_2_d0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    agg_result_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    agg_result_1_ce0 : OUT STD_LOGIC;
    agg_result_1_we0 : OUT STD_LOGIC;
    agg_result_1_d0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    agg_result_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    agg_result_0_ce0 : OUT STD_LOGIC;
    agg_result_0_we0 : OUT STD_LOGIC;
    agg_result_0_d0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    A_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_0_ce0 : OUT STD_LOGIC;
    A_0_q0 : IN STD_LOGIC_VECTOR (24 downto 0);
    conv7_i : IN STD_LOGIC_VECTOR (24 downto 0);
    conv7_i_1 : IN STD_LOGIC_VECTOR (24 downto 0);
    conv7_i_2 : IN STD_LOGIC_VECTOR (24 downto 0);
    conv7_i_3 : IN STD_LOGIC_VECTOR (24 downto 0) );
end;


architecture behav of top_matmul_10ul_1ul_4ul_Pipeline_VITIS_LOOP_71_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln71_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv7_i_3_cast_fu_179_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal conv7_i_3_cast_reg_284 : STD_LOGIC_VECTOR (49 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal conv7_i_2_cast_fu_183_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal conv7_i_2_cast_reg_289 : STD_LOGIC_VECTOR (49 downto 0);
    signal conv7_i_1_cast_fu_187_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal conv7_i_1_cast_reg_294 : STD_LOGIC_VECTOR (49 downto 0);
    signal conv7_i_cast_fu_191_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal conv7_i_cast_reg_299 : STD_LOGIC_VECTOR (49 downto 0);
    signal zext_ln71_fu_215_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln71_reg_307 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_04_fu_70 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_12_fu_209_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (3 downto 0);
    signal A_0_ce0_local : STD_LOGIC;
    signal agg_result_0_we0_local : STD_LOGIC;
    signal agg_result_0_ce0_local : STD_LOGIC;
    signal agg_result_1_we0_local : STD_LOGIC;
    signal agg_result_1_ce0_local : STD_LOGIC;
    signal agg_result_2_we0_local : STD_LOGIC;
    signal agg_result_2_ce0_local : STD_LOGIC;
    signal agg_result_3_we0_local : STD_LOGIC;
    signal agg_result_3_ce0_local : STD_LOGIC;
    signal mul_ln79_fu_163_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal conv_i_fu_225_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal mul_ln79_fu_163_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln79_71_fu_167_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln79_71_fu_167_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln79_72_fu_171_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln79_72_fu_171_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln79_73_fu_175_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln79_73_fu_175_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln79_fu_163_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal mul_ln79_71_fu_167_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal mul_ln79_72_fu_171_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal mul_ln79_73_fu_175_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_mul_25s_25s_50_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (24 downto 0);
        dout : OUT STD_LOGIC_VECTOR (49 downto 0) );
    end component;


    component top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_25s_25s_50_1_1_U734 : component top_mul_25s_25s_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 25,
        dout_WIDTH => 50)
    port map (
        din0 => mul_ln79_fu_163_p0,
        din1 => mul_ln79_fu_163_p1,
        dout => mul_ln79_fu_163_p2);

    mul_25s_25s_50_1_1_U735 : component top_mul_25s_25s_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 25,
        dout_WIDTH => 50)
    port map (
        din0 => mul_ln79_71_fu_167_p0,
        din1 => mul_ln79_71_fu_167_p1,
        dout => mul_ln79_71_fu_167_p2);

    mul_25s_25s_50_1_1_U736 : component top_mul_25s_25s_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 25,
        dout_WIDTH => 50)
    port map (
        din0 => mul_ln79_72_fu_171_p0,
        din1 => mul_ln79_72_fu_171_p1,
        dout => mul_ln79_72_fu_171_p2);

    mul_25s_25s_50_1_1_U737 : component top_mul_25s_25s_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 25,
        dout_WIDTH => 50)
    port map (
        din0 => mul_ln79_73_fu_175_p0,
        din1 => mul_ln79_73_fu_175_p1,
        dout => mul_ln79_73_fu_175_p2);

    flow_control_loop_pipe_sequential_init_U : component top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_04_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln71_fu_203_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_04_fu_70 <= i_12_fu_209_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_04_fu_70 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                conv7_i_1_cast_reg_294 <= conv7_i_1_cast_fu_187_p1;
                conv7_i_2_cast_reg_289 <= conv7_i_2_cast_fu_183_p1;
                conv7_i_3_cast_reg_284 <= conv7_i_3_cast_fu_179_p1;
                conv7_i_cast_reg_299 <= conv7_i_cast_fu_191_p1;
                    zext_ln71_reg_307(3 downto 0) <= zext_ln71_fu_215_p1(3 downto 0);
            end if;
        end if;
    end process;
    zext_ln71_reg_307(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_0_address0 <= zext_ln71_fu_215_p1(4 - 1 downto 0);
    A_0_ce0 <= A_0_ce0_local;

    A_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_0_ce0_local <= ap_const_logic_1;
        else 
            A_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_0_address0 <= zext_ln71_reg_307(4 - 1 downto 0);
    agg_result_0_ce0 <= agg_result_0_ce0_local;

    agg_result_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            agg_result_0_ce0_local <= ap_const_logic_1;
        else 
            agg_result_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_0_d0 <= mul_ln79_fu_163_p2(41 downto 17);
    agg_result_0_we0 <= agg_result_0_we0_local;

    agg_result_0_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            agg_result_0_we0_local <= ap_const_logic_1;
        else 
            agg_result_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_1_address0 <= zext_ln71_reg_307(4 - 1 downto 0);
    agg_result_1_ce0 <= agg_result_1_ce0_local;

    agg_result_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            agg_result_1_ce0_local <= ap_const_logic_1;
        else 
            agg_result_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_1_d0 <= mul_ln79_71_fu_167_p2(41 downto 17);
    agg_result_1_we0 <= agg_result_1_we0_local;

    agg_result_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            agg_result_1_we0_local <= ap_const_logic_1;
        else 
            agg_result_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_2_address0 <= zext_ln71_reg_307(4 - 1 downto 0);
    agg_result_2_ce0 <= agg_result_2_ce0_local;

    agg_result_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            agg_result_2_ce0_local <= ap_const_logic_1;
        else 
            agg_result_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_2_d0 <= mul_ln79_72_fu_171_p2(41 downto 17);
    agg_result_2_we0 <= agg_result_2_we0_local;

    agg_result_2_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            agg_result_2_we0_local <= ap_const_logic_1;
        else 
            agg_result_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_3_address0 <= zext_ln71_reg_307(4 - 1 downto 0);
    agg_result_3_ce0 <= agg_result_3_ce0_local;

    agg_result_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            agg_result_3_ce0_local <= ap_const_logic_1;
        else 
            agg_result_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_3_d0 <= mul_ln79_73_fu_175_p2(41 downto 17);
    agg_result_3_we0 <= agg_result_3_we0_local;

    agg_result_3_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            agg_result_3_we0_local <= ap_const_logic_1;
        else 
            agg_result_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln71_fu_203_p2)
    begin
        if (((icmp_ln71_fu_203_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_04_fu_70, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i <= i_04_fu_70;
        end if; 
    end process;

        conv7_i_1_cast_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i_1),50));

        conv7_i_2_cast_fu_183_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i_2),50));

        conv7_i_3_cast_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i_3),50));

        conv7_i_cast_fu_191_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i),50));

        conv_i_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(A_0_q0),50));

    i_12_fu_209_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv4_1));
    icmp_ln71_fu_203_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv4_A) else "0";
    mul_ln79_71_fu_167_p0 <= conv_i_fu_225_p1(25 - 1 downto 0);
    mul_ln79_71_fu_167_p1 <= conv7_i_1_cast_reg_294(25 - 1 downto 0);
    mul_ln79_72_fu_171_p0 <= conv_i_fu_225_p1(25 - 1 downto 0);
    mul_ln79_72_fu_171_p1 <= conv7_i_2_cast_reg_289(25 - 1 downto 0);
    mul_ln79_73_fu_175_p0 <= conv_i_fu_225_p1(25 - 1 downto 0);
    mul_ln79_73_fu_175_p1 <= conv7_i_3_cast_reg_284(25 - 1 downto 0);
    mul_ln79_fu_163_p0 <= conv_i_fu_225_p1(25 - 1 downto 0);
    mul_ln79_fu_163_p1 <= conv7_i_cast_reg_299(25 - 1 downto 0);
    zext_ln71_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),64));
end behav;
