#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("input_r_address0", 11, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("input_r_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("input_r_q0", 4096, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("y_true_address0", 11, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("y_true_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("y_true_q0", 640, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("weights_l0_address0", 6, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("weights_l0_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("weights_l0_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("weights_l0_d0", 4096, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("weights_l0_q0", 4096, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("weights_l1_address0", 3, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("weights_l1_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("weights_l1_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("weights_l1_d0", 4096, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("weights_l1_q0", 4096, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("weights_l2_i", 4096, hls_in, 4, "ap_ovld", "in_data", 1),
	Port_Property("weights_l2_o", 4096, hls_out, 4, "ap_ovld", "out_data", 1),
	Port_Property("weights_l2_o_ap_vld", 1, hls_out, 4, "ap_ovld", "out_vld", 1),
	Port_Property("weights_l3_address0", 4, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("weights_l3_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("weights_l3_we0", 1, hls_out, 5, "ap_memory", "mem_we", 1),
	Port_Property("weights_l3_d0", 512, hls_out, 5, "ap_memory", "mem_din", 1),
	Port_Property("weights_l3_q0", 512, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("biases_l0_i", 4096, hls_in, 6, "ap_ovld", "in_data", 1),
	Port_Property("biases_l0_o", 4096, hls_out, 6, "ap_ovld", "out_data", 1),
	Port_Property("biases_l0_o_ap_vld", 1, hls_out, 6, "ap_ovld", "out_vld", 1),
	Port_Property("biases_l1_i", 512, hls_in, 7, "ap_ovld", "in_data", 1),
	Port_Property("biases_l1_o", 512, hls_out, 7, "ap_ovld", "out_data", 1),
	Port_Property("biases_l1_o_ap_vld", 1, hls_out, 7, "ap_ovld", "out_vld", 1),
	Port_Property("biases_l2_i", 512, hls_in, 8, "ap_ovld", "in_data", 1),
	Port_Property("biases_l2_o", 512, hls_out, 8, "ap_ovld", "out_data", 1),
	Port_Property("biases_l2_o_ap_vld", 1, hls_out, 8, "ap_ovld", "out_vld", 1),
	Port_Property("biases_l3_i", 640, hls_in, 9, "ap_ovld", "in_data", 1),
	Port_Property("biases_l3_o", 640, hls_out, 9, "ap_ovld", "out_data", 1),
	Port_Property("biases_l3_o_ap_vld", 1, hls_out, 9, "ap_ovld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "accelerator";
