// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_softmax_10_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        agg_result_0_address0,
        agg_result_0_ce0,
        agg_result_0_we0,
        agg_result_0_d0,
        agg_result_0_address1,
        agg_result_0_ce1,
        agg_result_0_we1,
        agg_result_0_d1,
        agg_result_0_q1,
        net_0_address0,
        net_0_ce0,
        net_0_q0
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] agg_result_0_address0;
output   agg_result_0_ce0;
output   agg_result_0_we0;
output  [24:0] agg_result_0_d0;
output  [3:0] agg_result_0_address1;
output   agg_result_0_ce1;
output   agg_result_0_we1;
output  [24:0] agg_result_0_d1;
input  [24:0] agg_result_0_q1;
output  [3:0] net_0_address0;
output   net_0_ce0;
input  [24:0] net_0_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] agg_result_0_address0;
reg agg_result_0_ce0;
reg agg_result_0_we0;
reg[24:0] agg_result_0_d0;
reg[3:0] agg_result_0_address1;
reg agg_result_0_ce1;
reg[3:0] net_0_address0;
reg net_0_ce0;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [24:0] maxLogit_reg_621;
wire    ap_CS_fsm_state2;
wire   [3:0] add_ln128_fu_325_p2;
reg   [3:0] add_ln128_reg_632;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln128_fu_331_p1;
reg   [63:0] zext_ln128_reg_637;
wire   [24:0] sum_fu_342_p3;
reg   [24:0] sum_reg_647;
wire   [21:0] select_ln86_fu_380_p3;
reg  signed [21:0] select_ln86_reg_652;
wire    ap_CS_fsm_state7;
wire   [7:0] int_part_fu_463_p3;
reg   [7:0] int_part_reg_657;
wire    ap_CS_fsm_state8;
wire   [6:0] trunc_ln91_fu_471_p1;
reg   [6:0] trunc_ln91_reg_662;
wire  signed [24:0] frac_fu_483_p2;
reg  signed [24:0] frac_reg_668;
reg   [0:0] tmp_7_reg_678;
reg   [24:0] frac_approx_reg_682;
wire    ap_CS_fsm_state11;
reg   [22:0] trunc_ln95_1_reg_688;
wire   [0:0] icmp_ln100_fu_537_p2;
reg   [0:0] icmp_ln100_reg_693;
wire   [6:0] sub_i23_fu_542_p2;
reg   [6:0] sub_i23_reg_697;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_done;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_idle;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_ready;
wire   [3:0] grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_net_0_address0;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_net_0_ce0;
wire   [24:0] grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_maxLogit_1_out;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_maxLogit_1_out_ap_vld;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_done;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_idle;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_ready;
wire   [3:0] grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_address0;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_ce0;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_we0;
wire   [24:0] grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_d0;
wire   [3:0] grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_address1;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_ce1;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_done;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_idle;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_ready;
wire   [24:0] grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_phi_ln102_out;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_phi_ln102_out_ap_vld;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_done;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_idle;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_ready;
wire   [22:0] grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_phi_ln107_out;
wire    grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_phi_ln107_out_ap_vld;
wire  signed [24:0] sext_ln105_fu_555_p1;
reg   [24:0] ap_phi_mux_result_1_phi_fu_258_p6;
reg   [24:0] result_1_reg_255;
wire    ap_CS_fsm_state13;
reg    grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start_reg;
wire   [0:0] icmp_ln128_fu_319_p2;
wire    ap_CS_fsm_state15;
reg    grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state5;
reg   [24:0] sum_1_fu_104;
wire   [24:0] sum_2_fu_560_p2;
reg   [3:0] i_6_fu_108;
reg    agg_result_0_we1_local;
reg    agg_result_0_ce1_local;
reg   [3:0] agg_result_0_address1_local;
reg    agg_result_0_we0_local;
reg   [24:0] agg_result_0_d0_local;
reg    agg_result_0_ce0_local;
reg   [3:0] agg_result_0_address0_local;
reg    net_0_ce0_local;
reg   [3:0] net_0_address0_local;
wire   [0:0] icmp_ln137_fu_336_p2;
wire   [24:0] x_fu_351_p2;
wire   [0:0] icmp_ln131_fu_356_p2;
wire   [24:0] x_1_fu_362_p3;
wire   [0:0] icmp_ln86_fu_374_p2;
wire   [21:0] trunc_ln130_fu_370_p1;
wire   [18:0] mul_ln88_fu_391_p1;
wire   [40:0] mul_ln88_fu_391_p2;
wire   [23:0] y_fu_397_p4;
wire   [6:0] tmp_1_fu_411_p4;
wire   [16:0] tmp_4_fu_433_p4;
wire  signed [7:0] sext_ln91_fu_421_p1;
wire   [0:0] icmp_ln91_fu_443_p2;
wire   [7:0] add_ln91_fu_449_p2;
wire   [0:0] tmp_fu_425_p3;
wire   [7:0] select_ln91_fu_455_p3;
wire  signed [24:0] sext_ln88_1_fu_407_p1;
wire   [24:0] shl_ln_fu_475_p3;
wire  signed [39:0] grp_fu_575_p3;
wire   [58:0] mul_ln95_1_fu_296_p2;
wire   [58:0] add_ln95_1_fu_509_p2;
wire   [14:0] grp_fu_575_p1;
wire   [33:0] grp_fu_575_p2;
wire    ap_CS_fsm_state10;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start_reg = 1'b0;
#0 grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start_reg = 1'b0;
#0 grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start_reg = 1'b0;
#0 grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start_reg = 1'b0;
#0 sum_1_fu_104 = 25'd0;
#0 i_6_fu_108 = 4'd0;
end

top_softmax_10_Pipeline_VITIS_LOOP_120_1 grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start),
    .ap_done(grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_done),
    .ap_idle(grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_idle),
    .ap_ready(grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_ready),
    .maxLogit(maxLogit_reg_621),
    .net_0_address0(grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_net_0_address0),
    .net_0_ce0(grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_net_0_ce0),
    .net_0_q0(net_0_q0),
    .maxLogit_1_out(grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_maxLogit_1_out),
    .maxLogit_1_out_ap_vld(grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_maxLogit_1_out_ap_vld)
);

top_softmax_10_Pipeline_VITIS_LOOP_138_3 grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start),
    .ap_done(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_done),
    .ap_idle(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_idle),
    .ap_ready(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_ready),
    .agg_result_0_address0(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_address0),
    .agg_result_0_ce0(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_ce0),
    .agg_result_0_we0(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_we0),
    .agg_result_0_d0(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_d0),
    .agg_result_0_address1(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_address1),
    .agg_result_0_ce1(grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_ce1),
    .agg_result_0_q1(agg_result_0_q1),
    .conv_i(sum_reg_647)
);

top_softmax_10_Pipeline_VITIS_LOOP_100_1 grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start),
    .ap_done(grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_done),
    .ap_idle(grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_idle),
    .ap_ready(grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_ready),
    .trunc_ln95_1(trunc_ln95_1_reg_688),
    .int_part(trunc_ln91_reg_662),
    .phi_ln102_out(grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_phi_ln102_out),
    .phi_ln102_out_ap_vld(grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_phi_ln102_out_ap_vld)
);

top_softmax_10_Pipeline_VITIS_LOOP_105_2 grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start),
    .ap_done(grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_done),
    .ap_idle(grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_idle),
    .ap_ready(grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_ready),
    .frac_approx(frac_approx_reg_682),
    .sub_i23(sub_i23_reg_697),
    .phi_ln107_out(grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_phi_ln107_out),
    .phi_ln107_out_ap_vld(grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_phi_ln107_out_ap_vld)
);

top_mul_40s_25s_59_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 59 ))
mul_40s_25s_59_1_1_U425(
    .din0(grp_fu_575_p3),
    .din1(frac_reg_668),
    .dout(mul_ln95_1_fu_296_p2)
);

top_mul_22s_19ns_41_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 19 ),
    .dout_WIDTH( 41 ))
mul_22s_19ns_41_1_1_U426(
    .din0(select_ln86_reg_652),
    .din1(mul_ln88_fu_391_p1),
    .dout(mul_ln88_fu_391_p2)
);

top_mac_muladd_25s_15ns_34ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 40 ))
mac_muladd_25s_15ns_34ns_40_4_1_U427(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(frac_fu_483_p2),
    .din1(grp_fu_575_p1),
    .din2(grp_fu_575_p2),
    .ce(1'b1),
    .dout(grp_fu_575_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_7_reg_678 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln100_fu_537_p2 == 1'd1))) begin
            grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start_reg <= 1'b1;
        end else if ((grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_ready == 1'b1)) begin
            grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_7_reg_678 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
            grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start_reg <= 1'b1;
        end else if ((grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_ready == 1'b1)) begin
            grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start_reg <= 1'b1;
        end else if ((grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_ready == 1'b1)) begin
            grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln128_fu_319_p2 == 1'd1))) begin
            grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start_reg <= 1'b1;
        end else if ((grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_ready == 1'b1)) begin
            grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_6_fu_108 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        i_6_fu_108 <= add_ln128_reg_632;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_reg_678 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln100_fu_537_p2 == 1'd0))) begin
        result_1_reg_255 <= {{add_ln95_1_fu_509_p2[58:34]}};
    end else if (((tmp_7_reg_678 == 1'd0) & (1'b1 == ap_CS_fsm_state13) & (icmp_ln100_reg_693 == 1'd1))) begin
        result_1_reg_255 <= grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_phi_ln102_out;
    end else if (((tmp_7_reg_678 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        result_1_reg_255 <= sext_ln105_fu_555_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_1_fu_104 <= 25'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        sum_1_fu_104 <= sum_2_fu_560_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln128_reg_632 <= add_ln128_fu_325_p2;
        sum_reg_647 <= sum_fu_342_p3;
        zext_ln128_reg_637[3 : 0] <= zext_ln128_fu_331_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        frac_approx_reg_682 <= {{add_ln95_1_fu_509_p2[58:34]}};
        icmp_ln100_reg_693 <= icmp_ln100_fu_537_p2;
        sub_i23_reg_697 <= sub_i23_fu_542_p2;
        trunc_ln95_1_reg_688 <= {{add_ln95_1_fu_509_p2[56:34]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        frac_reg_668 <= frac_fu_483_p2;
        int_part_reg_657 <= int_part_fu_463_p3;
        tmp_7_reg_678 <= int_part_fu_463_p3[32'd7];
        trunc_ln91_reg_662 <= trunc_ln91_fu_471_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        maxLogit_reg_621 <= net_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        select_ln86_reg_652 <= select_ln86_fu_380_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        agg_result_0_address0 = grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_address0;
    end else begin
        agg_result_0_address0 = agg_result_0_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        agg_result_0_address0_local = zext_ln128_reg_637;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        agg_result_0_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        agg_result_0_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        agg_result_0_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        agg_result_0_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        agg_result_0_address0_local = 64'd1;
    end else begin
        agg_result_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        agg_result_0_address1 = grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_address1;
    end else begin
        agg_result_0_address1 = agg_result_0_address1_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        agg_result_0_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        agg_result_0_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        agg_result_0_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        agg_result_0_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        agg_result_0_address1_local = 64'd0;
    end else begin
        agg_result_0_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        agg_result_0_ce0 = grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_ce0;
    end else begin
        agg_result_0_ce0 = agg_result_0_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state13) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_done == 1'b1)))) begin
        agg_result_0_ce0_local = 1'b1;
    end else begin
        agg_result_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        agg_result_0_ce1 = grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_ce1;
    end else begin
        agg_result_0_ce1 = agg_result_0_ce1_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_done == 1'b1)))) begin
        agg_result_0_ce1_local = 1'b1;
    end else begin
        agg_result_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        agg_result_0_d0 = grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_d0;
    end else begin
        agg_result_0_d0 = agg_result_0_d0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        agg_result_0_d0_local = ap_phi_mux_result_1_phi_fu_258_p6;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        agg_result_0_d0_local = 25'd0;
    end else begin
        agg_result_0_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        agg_result_0_we0 = grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_agg_result_0_we0;
    end else begin
        agg_result_0_we0 = agg_result_0_we0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state13) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_done == 1'b1)))) begin
        agg_result_0_we0_local = 1'b1;
    end else begin
        agg_result_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_done == 1'b1)))) begin
        agg_result_0_we1_local = 1'b1;
    end else begin
        agg_result_0_we1_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state15) & (grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        if (((tmp_7_reg_678 == 1'd0) & (icmp_ln100_reg_693 == 1'd1))) begin
            ap_phi_mux_result_1_phi_fu_258_p6 = grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_phi_ln102_out;
        end else if ((tmp_7_reg_678 == 1'd1)) begin
            ap_phi_mux_result_1_phi_fu_258_p6 = sext_ln105_fu_555_p1;
        end else begin
            ap_phi_mux_result_1_phi_fu_258_p6 = result_1_reg_255;
        end
    end else begin
        ap_phi_mux_result_1_phi_fu_258_p6 = result_1_reg_255;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        net_0_address0 = grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_net_0_address0;
    end else begin
        net_0_address0 = net_0_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        net_0_address0_local = zext_ln128_fu_331_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        net_0_address0_local = 64'd0;
    end else begin
        net_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        net_0_ce0 = grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_net_0_ce0;
    end else begin
        net_0_ce0 = net_0_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        net_0_ce0_local = 1'b1;
    end else begin
        net_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln128_fu_319_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((tmp_7_reg_678 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln100_fu_537_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((tmp_7_reg_678 == 1'd0) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln100_fu_537_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln128_fu_325_p2 = (i_6_fu_108 + 4'd1);

assign add_ln91_fu_449_p2 = ($signed(sext_ln91_fu_421_p1) + $signed(8'd1));

assign add_ln95_1_fu_509_p2 = (mul_ln95_1_fu_296_p2 + 59'd2251799813685248);

assign agg_result_0_d1 = 25'd0;

assign agg_result_0_we1 = agg_result_0_we1_local;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign frac_fu_483_p2 = ($signed(sext_ln88_1_fu_407_p1) - $signed(shl_ln_fu_475_p3));

assign grp_fu_575_p1 = 40'd31483;

assign grp_fu_575_p2 = 40'd11907366912;

assign grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start = grp_softmax_10_Pipeline_VITIS_LOOP_100_1_fu_282_ap_start_reg;

assign grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start = grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_ap_start_reg;

assign grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start = grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_ap_start_reg;

assign grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start = grp_softmax_10_Pipeline_VITIS_LOOP_138_3_fu_275_ap_start_reg;

assign icmp_ln100_fu_537_p2 = (($signed(int_part_reg_657) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln128_fu_319_p2 = ((i_6_fu_108 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln131_fu_356_p2 = (($signed(x_fu_351_p2) < $signed(25'd32243712)) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_336_p2 = ((sum_1_fu_104 == 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_374_p2 = (($signed(x_1_fu_362_p3) > $signed(25'd1310720)) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_443_p2 = ((tmp_4_fu_433_p4 != 17'd0) ? 1'b1 : 1'b0);

assign int_part_fu_463_p3 = ((tmp_fu_425_p3[0:0] == 1'b1) ? select_ln91_fu_455_p3 : sext_ln91_fu_421_p1);

assign mul_ln88_fu_391_p1 = 41'd189096;

assign select_ln86_fu_380_p3 = ((icmp_ln86_fu_374_p2[0:0] == 1'b1) ? 22'd1310720 : trunc_ln130_fu_370_p1);

assign select_ln91_fu_455_p3 = ((icmp_ln91_fu_443_p2[0:0] == 1'b1) ? add_ln91_fu_449_p2 : sext_ln91_fu_421_p1);

assign sext_ln105_fu_555_p1 = $signed(grp_softmax_10_Pipeline_VITIS_LOOP_105_2_fu_289_phi_ln107_out);

assign sext_ln88_1_fu_407_p1 = $signed(y_fu_397_p4);

assign sext_ln91_fu_421_p1 = $signed(tmp_1_fu_411_p4);

assign shl_ln_fu_475_p3 = {{int_part_fu_463_p3}, {17'd0}};

assign sub_i23_fu_542_p2 = (7'd0 - trunc_ln91_reg_662);

assign sum_2_fu_560_p2 = (ap_phi_mux_result_1_phi_fu_258_p6 + sum_1_fu_104);

assign sum_fu_342_p3 = ((icmp_ln137_fu_336_p2[0:0] == 1'b1) ? 25'd131072 : sum_1_fu_104);

assign tmp_1_fu_411_p4 = {{mul_ln88_fu_391_p2[40:34]}};

assign tmp_4_fu_433_p4 = {{mul_ln88_fu_391_p2[33:17]}};

assign tmp_fu_425_p3 = mul_ln88_fu_391_p2[32'd40];

assign trunc_ln130_fu_370_p1 = x_1_fu_362_p3[21:0];

assign trunc_ln91_fu_471_p1 = int_part_fu_463_p3[6:0];

assign x_1_fu_362_p3 = ((icmp_ln131_fu_356_p2[0:0] == 1'b1) ? 25'd32243712 : x_fu_351_p2);

assign x_fu_351_p2 = (net_0_q0 - grp_softmax_10_Pipeline_VITIS_LOOP_120_1_fu_267_maxLogit_1_out);

assign y_fu_397_p4 = {{mul_ln88_fu_391_p2[40:17]}};

assign zext_ln128_fu_331_p1 = i_6_fu_108;

always @ (posedge ap_clk) begin
    zext_ln128_reg_637[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //top_softmax_10_s
